apiVersion: v1
kind: Service
metadata:
  name: feature-targeting
  labels:
    app: feature-targeting
spec:
  ports:
    - port: 50051
      name: grpc
  selector:
    app: feature-targeting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-targeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature-targeting
  template:
    metadata:
      labels:
        app: feature-targeting
    spec:
      containers:
        - name: feature-targeting
          image: redbadger/feature-targeting-adapter-istio
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
