apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
spec:
  profile: default
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: false
