apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todomvc-api
spec:
  hosts:
    - api.todomvc.localhost
  gateways:
    - istio-system/ingressgateway
  http:
    - route:
        - destination:
            port:
              number: 3030
            host: todomvc-api
