apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: istiocontrolplane
spec:
  profile: demo
  values:
    global:
      policyCheckFailOpen: true
    pilot:
      policy:
        enabled: true
    gateways:
      istio-ingressgateway:
        type: NodePort
        ports:
          - name: http2
            port: 80
            targetPort: 80
            nodePort: 32444
          - name: status-port
            port: 15020
            targetPort: 15020
          - name: https
            port: 443
          - name: kiali
            port: 15029
            targetPort: 15029
          - name: prometheus
            port: 15030
            targetPort: 15030
          - name: grafana
            port: 15031
            targetPort: 15031
          - name: tracing
            port: 15032
            targetPort: 15032
          - name: tls
            port: 15443
            targetPort: 15443
