apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: feature-targeting
spec:
  adapter: feature-targeting
  connection:
    address: feature-targeting:50051
  params:
    explicit_targeting:
      override_header: x-features
      hostname_pattern: "*.echo.localhost"
