[package]
name = "todomvc_api"
version = "0.1.0"
authors = ["Stuart Harris <stuart.harris@red-badger.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
async-graphql = "1.16.15"
async-graphql-tide = "1.16.12"
async-std = { version = "1.6.2", features = ["attributes"] }
http-types = "2.3.0"
sqlx = { version = "0.4.0-beta.1", features = [ "offline", "postgres", "macros", "uuid" ] }
structopt = "0.3.15"
tide = "0.12.0"
uuid = "0.8.1"
