[package]
name = "todomvc_api"
version = "0.1.0"
authors = ["Stuart Harris <stuart.harris@red-badger.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
async-graphql = "1.17.4"
async-graphql-tide = "1.17.4"
async-std = { version = "1.6.2", features = ["attributes"] }
base64 = "0.12.3"
http-types = "2.4.0"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
sqlx = { version = "0.4.0-beta.1", features = [ "offline", "postgres", "macros", "uuid" ] }
structopt = "0.3.16"
tide = "0.13.0"
uuid = "0.8.1"
