apiVersion: red-badger.com/v1alpha1
kind: FeatureTargetConfig
metadata:
  name: echo
spec:
  selector:
    app: echo
  configuration: |
    {
      "header_name": "x-features",
      "explicit": [
        {
          "_extract": "list",
          "attribute": "x-feature-override"
        },
        {
          "_extract": "pattern",
          "attribute": ":authority",
          "pattern": "f-*.localhost"
        }
      ],
      "implicit" : [
        {
          "name":"english",
          "rule": {
            "any_in": {
                "list": { "constant": ["en","en-US","en-GB"] },
                "values": {
                    "http_quality_value": { "attribute": "accept-language" }
                }
            }
          }
        }
      ]
    }
