[package]
name = "todomvc_web_server"
version = "0.1.0"
authors = ["Stuart Harris <stuart.harris@red-badger.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
async-std = { version = "1.6.2", features = ["attributes"] }
base64 = "0.12.3"
failure = "0.1.8"
http-types = { version = "2.3.0", features = ["hyperium_http"] }
openidconnect = { version = "1.0.1", features = ["futures-03"], default-features = false }
serde = "1.0.114"
serde_json = "1.0.57"
structopt = "0.3.15"
surf = { git = "https://github.com/http-rs/surf" }
thiserror = "1.0.20"
tide = "0.12.0"
time = "0.2.16"
url = "2.1.1"
