[package]
name = "data-plane"
version = "0.1.0"
authors = ["Viktor Charypar <charypar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.106", features = ["derive"] }

[dev-dependencies]
test-case = "1.0.0"
lazy_static = "1.4.0"
