apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: feature-targeting
  namespace: istio-system
spec:
  template: feature-targeting
  params:
    method: request.method | ""
    path: api.operation | request.path | ""
    headers: request.headers
