apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: feature-targeting
spec:
  match: source.labels["istio"] == "ingressgateway"
  actions:
    - handler: feature-targeting.istio-system
      instances:
        - feature-targeting
      name: x
  requestHeaderOperations:
    - name: X-Features
      values:
        - x.output.features
