apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: feature-targeting
spec:
  match: context.reporter.kind == "outbound" && source.labels["istio"] == "ingressgateway"
  actions:
    - handler: feature-targeting.istio-system
      instances:
        - feature-targeting
      name: x
  requestHeaderOperations:
    - name: x-features
      values:
        - x.output.features
