apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: feature-targeting
spec:
  actions:
    - handler: feature-targeting.istio-system
      instances:
        - feature-targeting
      name: x
  requestHeaderOperations:
    - name: features
      values:
        - x.output.value
