apiVersion: v1
kind: Service
metadata:
  name: feature-targeting
  labels:
    app: feature-targeting
    service: feature-targeting
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: feature-targeting
